# Generated by Django 4.2 on 2026-04-13 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_reservas', '0002_alter_mesa_id_alter_reserva_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Hamburguesas', 'Hamburguesas'), ('Pizzas', 'Pizzas'), ('Hot Dogs', 'Hot Dogs'), ('Bebidas', 'Bebidas'), ('Postres', 'Postres')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{7,}$', 'Teléfono inválido')])),
                ('tipo', models.CharField(choices=[('Para Retirar', 'Para Retirar'), ('Comer en Mesa', 'Comer en Mesa')], max_length=20)),
                ('fecha_hora_retiro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparando', 'Preparando'), ('Lista', 'Lista'), ('Entregada', 'Entregada')], default='Pendiente', max_length=15)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='api_reservas.mesa')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_reservas.menuitem')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_reservas.orden')),
            ],
            options={
                'unique_together': {('orden', 'item_menu')},
            },
        ),
    ]
