# Generated by Django 6.0.4 on 2026-04-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reservas', '0004_alter_menuitem_id_alter_mesa_id_alter_orden_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, unique=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('cerrado', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Horarios del Restaurante',
                'ordering': ['id'],
            },
        ),
    ]
